use strict;
use warnings;
use Test::More;

# generated by Dist::Zilla::Plugin::Test::PodSpelling 2.006002
use Test::Spelling 0.12;
use Pod::Wordlist;


add_stopwords(<DATA>);
all_pod_files_spelling_ok( qw( bin lib  ) );
__DATA__
CA
UA
proxying
Christian
Hansen
chansen
David
Golden
dagolden
Alan
Gardner
gardner
Alessandro
Ghedini
al3xbio
Brad
Gilbert
bgills
Chris
Nehren
apeiron
Weyl
cweyl
Claes
Jakobsson
claes
Clinton
Gormley
clint
Craig
Berry
cberry
Mitchell
davem
Edward
Zborowski
ed
Jess
Robinson
castaway
Lukas
Eklund
leklund
Martin
Evans
mjegh
Bright
mlbright
Mike
Doherty
doherty
Petr
Písař
ppisar
Serguei
Trouchelle
stro
Syohei
YOSHIDA
syohex
Tony
Cook
tony
lib
HTTP
Tiny
