use strict;
use warnings;
use Test::More;

# generated by Dist::Zilla::Plugin::Test::PodSpelling 2.007000
use Test::Spelling 0.12;
use Pod::Wordlist;


add_stopwords(<DATA>);
all_pod_files_spelling_ok( qw( bin lib  ) );
__DATA__
irc
יובל
קוג
Yuval
Kogman
nothingmuch
Jesse
Luehrs
doy
Karen
Etheridge
ether
Peter
Rabbitson
ribasushi
Ricardo
Signes
rjbs
Mark
Fowler
mark
Graham
Knop
haarg
Dagfinn
Ilmari
Mannsåker
ilmari
Paul
Howarth
paul
Rudolf
Leermakers
rudolf
anaxagoras
walkeraj
awalker
chromatic
Alex
alex
cm
Andrew
Yates
ayates
David
Lowe
davidl
Glenn
cebjyre
Hans
Dieter
Pearcey
hdp
Jonathan
Yu
JAWNSY
Marc
Mims
marc
Stosberg
lib
Try
Tiny
