
BEGIN {
  unless ($ENV{AUTHOR_TESTING}) {
    require Test::More;
    Test::More::plan(skip_all => 'these tests are for testing by the author');
  }
}

use strict;
use warnings;
use Test::More;

# generated by Dist::Zilla::Plugin::Test::PodSpelling 2.007000
use Test::Spelling 0.12;
use Pod::Wordlist;


add_stopwords(<DATA>);
all_pod_files_spelling_ok( qw( bin lib  ) );
__DATA__
DROLSKY
DROLSKY's
PayPal
Rolsky
Rolsky's
CPAN
stacktrace
Dave
autarch
David
Dagfinn
Ilmari
Mannsåker
ilmari
Cantrell
david
Graham
Knop
haarg
Mark
Fowler
mark
Ricardo
Signes
rjbs
lib
Devel
StackTrace
Frame
